export const FOOD_STALLS_REQUEST = 'FOOD_STALLS_REQUEST';
export const FOOD_STALLS_SUCCESS = 'FOOD_STALLS_SUCCESS';
export const FOOD_STALLS_FAILURE = 'FOOD_STALLS_FAILURE';

export const FOOD_STALL_DETAILS_REQUEST = 'FOOD_STALL_DETAILS_REQUEST';
export const FOOD_STALL_DETAILS_SUCCESS = 'FOOD_STALL_DETAILS_SUCCESS';
export const FOOD_STALL_DETAILS_FAILURE = 'FOOD_STALL_DETAILS_FAILURE';

export const CREATE_FOOD_STALL_REQUEST = 'CREATE_FOOD_STALL_REQUEST';
export const CREATE_FOOD_STALL_SUCCESS = 'CREATE_FOOD_STALL_SUCCESS';
export const CREATE_FOOD_STALL_FAILURE = 'CREATE_FOOD_STALL_FAILURE';

export const UPDATE_FOOD_STALL_REQUEST = 'UPDATE_FOOD_STALL_REQUEST';
export const UPDATE_FOOD_STALL_SUCCESS = 'UPDATE_FOOD_STALL_SUCCESS';
export const UPDATE_FOOD_STALL_FAILURE = 'UPDATE_FOOD_STALL_FAILURE';

export const DELETE_FOOD_STALL_REQUEST = 'DELETE_FOOD_STALL_REQUEST';
export const DELETE_FOOD_STALL_SUCCESS = 'DELETE_FOOD_STALL_SUCCESS';
export const DELETE_FOOD_STALL_FAILURE = 'DELETE_FOOD_STALL_FAILURE';